#!/usr/bin/env python3
"""Generator: writes worldcup_pool/data/wc2026_top_scorer_candidates.json (48 WC2026 TLAs).

Source: official 2026 FIFA World Cup squads, compiled 2026-06-01 from Wikipedia
"2026 FIFA World Cup squads" + ESPN + federation announcements. Each list is the official
squad ordered attacker-weighted (forwards -> attacking mids/wingers -> mids -> defenders -> GK last)
so likely goalscorers surface first in the top-scorer picker.

Six squads were still preliminary at compile time (final FIFA confirmation 2026-06-02) and carry
their full announced preliminary list: TUR, IRN, QAT, JOR, SEN, GHA. Re-run after the official
cuts to trim those to the final 26.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))

from worldcup_pool.wc2026_official_groups import official_wc2026_group_teams  # noqa: E402

_OUT = _REPO / "worldcup_pool" / "data" / "wc2026_top_scorer_candidates.json"

# Official WC2026 squads, attacker-weighted. (compiled 2026-06-01)
POOLS: dict[str, list[str]] = {
    "ALG": [
        "Mohamed Amoura",
        "Riyad Mahrez",
        "Amine Gouiri",
        "Anis Hadj Moussa",
        "Adil Boulbina",
        "Nadhir Benbouali",
        "Farès Ghedjemis",
        "Farès Chaïbi",
        "Houssem Aouar",
        "Ibrahim Maza",
        "Hicham Boudaoui",
        "Nabil Bentaleb",
        "Ramiz Zerrouki",
        "Yacine Titraoui",
        "Rayan Aït-Nouri",
        "Ramy Bensebaini",
        "Aïssa Mandi",
        "Mohamed Amine Tougai",
        "Jaouen Hadjam",
        "Rafik Belghali",
        "Zineddine Belaïd",
        "Achref Abada",
        "Samir Chergui",
        "Luca Zidane",
        "Oussama Benbot",
        "Melvin Mastil"
    ],
    "ARG": [
        "Lionel Messi",
        "Lautaro Martínez",
        "Julián Álvarez",
        "José Manuel López",
        "Nicolás González",
        "Thiago Almada",
        "Giuliano Simeone",
        "Nico Paz",
        "Alexis Mac Allister",
        "Enzo Fernández",
        "Giovani Lo Celso",
        "Rodrigo De Paul",
        "Exequiel Palacios",
        "Leandro Paredes",
        "Valentín Barco",
        "Nahuel Molina",
        "Gonzalo Montiel",
        "Nicolás Tagliafico",
        "Cristian Romero",
        "Nicolás Otamendi",
        "Lisandro Martínez",
        "Leonardo Balerdi",
        "Facundo Medina",
        "Emiliano Martínez",
        "Gerónimo Rulli",
        "Juan Musso"
    ],
    "AUS": [
        "Mathew Leckie",
        "Awer Mabil",
        "Nestory Irankunda",
        "Mohamed Touré",
        "Nishan Velupillay",
        "Cristian Volpato",
        "Tete Yengi",
        "Jackson Irvine",
        "Ajdin Hrustic",
        "Connor Metcalfe",
        "Aiden O'Neill",
        "Paul Okon-Engstler",
        "Cammy Devlin",
        "Aziz Behich",
        "Miloš Degenek",
        "Harry Souttar",
        "Jordan Bos",
        "Cameron Burgess",
        "Jason Geria",
        "Alessandro Circati",
        "Kai Trewin",
        "Jacob Italiano",
        "Lucas Herrington",
        "Mathew Ryan",
        "Paul Izzo",
        "Patrick Beach"
    ],
    "AUT": [
        "Marko Arnautović",
        "Michael Gregoritsch",
        "Saša Kalajdžić",
        "Christoph Baumgartner",
        "Patrick Wimmer",
        "Romano Schmid",
        "Alessandro Schöpf",
        "Paul Wanner",
        "Carney Chukwuemeka",
        "Marcel Sabitzer",
        "Konrad Laimer",
        "Xaver Schlager",
        "Nicolas Seiwald",
        "Florian Grillitsch",
        "David Alaba",
        "Kevin Danso",
        "Philipp Lienhart",
        "David Affengruber",
        "Marco Friedl",
        "Stefan Posch",
        "Phillipp Mwene",
        "Alexander Prass",
        "Michael Svoboda",
        "Patrick Pentz",
        "Alexander Schlager",
        "Florian Wiegele"
    ],
    "BEL": [
        "Romelu Lukaku",
        "Leandro Trossard",
        "Jérémy Doku",
        "Charles De Ketelaere",
        "Dodi Lukebakio",
        "Alexis Saelemaekers",
        "Diego Moreira",
        "Matias Fernandez-Pardo",
        "Kevin De Bruyne",
        "Youri Tielemans",
        "Hans Vanaken",
        "Amadou Onana",
        "Nicolas Raskin",
        "Axel Witsel",
        "Thomas Meunier",
        "Timothy Castagne",
        "Arthur Theate",
        "Zeno Debast",
        "Koni De Winter",
        "Maxim De Cuyper",
        "Brandon Mechele",
        "Nathan Ngoy",
        "Joaquin Seys",
        "Thibaut Courtois",
        "Senne Lammens",
        "Mike Penders"
    ],
    "BIH": [
        "Edin Džeko",
        "Ermedin Demirović",
        "Samed Baždar",
        "Haris Tabaković",
        "Jovo Lukić",
        "Esmir Bajraktarević",
        "Kerim Alajbegović",
        "Amar Memić",
        "Amir Hadžiahmetović",
        "Benjamin Tahirović",
        "Armin Gigović",
        "Dženis Burnić",
        "Ivan Bašić",
        "Ivan Šunjić",
        "Ermin Mahmić",
        "Sead Kolašinac",
        "Amar Dedić",
        "Nikola Katić",
        "Dennis Hadžikadunić",
        "Tarik Muharemović",
        "Nihad Mujakić",
        "Stjepan Radeljić",
        "Nidal Čelik",
        "Nikola Vasilj",
        "Martin Zlomislić",
        "Osman Hadžikić"
    ],
    "BRA": [
        "Vinícius Júnior",
        "Neymar",
        "Raphinha",
        "Matheus Cunha",
        "Endrick",
        "Luiz Henrique",
        "Gabriel Martinelli",
        "Igor Thiago",
        "Rayan",
        "Lucas Paquetá",
        "Bruno Guimarães",
        "Casemiro",
        "Fabinho",
        "Danilo Santos",
        "Wesley",
        "Danilo Luiz",
        "Marquinhos",
        "Gabriel Magalhães",
        "Bremer",
        "Léo Pereira",
        "Roger Ibáñez",
        "Alex Sandro",
        "Douglas Santos",
        "Alisson",
        "Ederson",
        "Weverton"
    ],
    "CAN": [
        "Jonathan David",
        "Cyle Larin",
        "Tani Oluwaseyi",
        "Promise David",
        "Tajon Buchanan",
        "Jacob Shaffelburg",
        "Liam Millar",
        "Jonathan Osorio",
        "Ali Ahmed",
        "Stephen Eustáquio",
        "Ismaël Koné",
        "Mathieu Choinière",
        "Nathan Saliba",
        "Alphonso Davies",
        "Alistair Johnston",
        "Moïse Bombito",
        "Derek Cornelius",
        "Joel Waterman",
        "Richie Laryea",
        "Niko Sigur",
        "Luc de Fougerolles",
        "Alfie Jones",
        "Dayne St. Clair",
        "Maxime Crépeau",
        "Owen Goodman"
    ],
    "CIV": [
        "Nicolas Pépé",
        "Amad Diallo",
        "Simon Adingra",
        "Evann Guessand",
        "Elye Wahi",
        "Ange-Yoan Bonny",
        "Oumar Diakité",
        "Yan Diomande",
        "Bazoumana Touré",
        "Franck Kessié",
        "Ibrahim Sangaré",
        "Seko Fofana",
        "Jean Michaël Seri",
        "Christ Inao Oulaï",
        "Parfait Guiagon",
        "Wilfried Singo",
        "Odilon Kossounou",
        "Evan Ndicka",
        "Emmanuel Agbadou",
        "Guéla Doué",
        "Ousmane Diomande",
        "Ghislain Konan",
        "Christopher Opéri",
        "Yahia Fofana",
        "Alban Lafont",
        "Mohamed Koné"
    ],
    "COD": [
        "Cédric Bakambu",
        "Yoane Wissa",
        "Fiston Mayele",
        "Théo Bongonda",
        "Meschak Elia",
        "Nathanaël Mbuku",
        "Simon Banza",
        "Gaël Kakuta",
        "Noah Sadiki",
        "Edo Kayembe",
        "Charles Pickel",
        "Samuel Moutoussamy",
        "Aaron Tshibola",
        "Ngal'ayel Mukau",
        "Brian Cipenga",
        "Chancel Mbemba",
        "Arthur Masuaku",
        "Gédéon Kalulu",
        "Joris Kayembe",
        "Dylan Batubinsika",
        "Axel Tuanzebe",
        "Aaron Wan-Bissaka",
        "Steve Kapuadi",
        "Lionel Mpasi",
        "Timothy Fayulu",
        "Matthieu Epolo"
    ],
    "COL": [
        "Luis Díaz",
        "Jhon Córdoba",
        "Luis Suárez",
        "Cucho Hernández",
        "Andrés Gómez",
        "James Rodríguez",
        "Juan Fernando Quintero",
        "Jhon Arias",
        "Jorge Carrascal",
        "Jaminton Campaz",
        "Jefferson Lerma",
        "Richard Ríos",
        "Kevin Castaño",
        "Juan Portilla",
        "Gustavo Puerta",
        "Daniel Muñoz",
        "Davinson Sánchez",
        "Yerry Mina",
        "Jhon Lucumí",
        "Johan Mojica",
        "Deiver Machado",
        "Santiago Arias",
        "Willer Ditta",
        "David Ospina",
        "Camilo Vargas",
        "Álvaro Montero"
    ],
    "CPV": [
        "Ryan Mendes",
        "Garry Rodrigues",
        "Willy Semedo",
        "Jovane Cabral",
        "Gilson Benchimol",
        "Dailon Livramento",
        "Hélio Varela",
        "Nuno da Costa",
        "Jamiro Monteiro",
        "Kevin Pina",
        "Deroy Duarte",
        "Telmo Arcanjo",
        "Laros Duarte",
        "Yannick Semedo",
        "Stopira",
        "Roberto Lopes",
        "João Paulo",
        "Diney",
        "Logan Costa",
        "Steven Moreira",
        "Wagner Pina",
        "Sidny Lopes Cabral",
        "Kelvin Pires",
        "Vozinha",
        "Márcio Rosa",
        "CJ dos Santos"
    ],
    "CRO": [
        "Andrej Kramarić",
        "Ante Budimir",
        "Petar Musa",
        "Igor Matanović",
        "Ivan Perišić",
        "Marco Pašalić",
        "Luka Modrić",
        "Mateo Kovačić",
        "Mario Pašalić",
        "Nikola Vlašić",
        "Luka Sučić",
        "Petar Sučić",
        "Martin Baturina",
        "Toni Fruk",
        "Kristijan Jakić",
        "Nikola Moro",
        "Joško Gvardiol",
        "Josip Stanišić",
        "Josip Šutalo",
        "Marin Pongračić",
        "Duje Ćaleta-Car",
        "Martin Erlić",
        "Luka Vušković",
        "Dominik Livaković",
        "Dominik Kotarski",
        "Ivor Pandur"
    ],
    "CUW": [
        "Jurgen Locadia",
        "Sontje Hansen",
        "Gervane Kastaneer",
        "Jearl Margaritha",
        "Jeremy Antonisse",
        "Kenji Gorre",
        "Brandley Kuwas",
        "Tahith Chong",
        "Tyrese Noslin",
        "Ar'jany Martha",
        "Livano Comenencia",
        "Kevin Felida",
        "Juninho Bacuna",
        "Leandro Bacuna",
        "Godfried Roemeratoe",
        "Riechedly Bazoer",
        "Joshua Brenet",
        "Sherel Floranus",
        "Armando Obispo",
        "Shurandy Sambo",
        "Roshon van Eijma",
        "Deveron Fonville",
        "Jurien Gaari",
        "Eloy Room",
        "Tyrick Bodak",
        "Trevor Doornbusch"
    ],
    "CZE": [
        "Patrik Schick",
        "Adam Hložek",
        "Jan Kuchta",
        "Mojmír Chytil",
        "Tomáš Chorý",
        "Pavel Šulc",
        "Lukáš Provod",
        "Denis Višinský",
        "Hugo Sochůrek",
        "Tomáš Souček",
        "Michal Sadílek",
        "Lukáš Červ",
        "Vladimír Darida",
        "Alexandr Sojka",
        "Vladimír Coufal",
        "Tomáš Holeš",
        "Ladislav Krejčí",
        "David Zima",
        "Jaroslav Zelený",
        "David Jurásek",
        "David Douděra",
        "Robin Hranáč",
        "Štěpán Chaloupek",
        "Matěj Kovář",
        "Jindřich Staněk",
        "Lukáš Horníček"
    ],
    "ECU": [
        "Enner Valencia",
        "Kevin Rodríguez",
        "Anthony Valencia",
        "Jordy Caicedo",
        "Nilson Angulo",
        "Jeremy Arévalo",
        "Gonzalo Plata",
        "Kendry Páez",
        "John Yeboah",
        "Alan Minda",
        "Yaimar Medina",
        "Moisés Caicedo",
        "Alan Franco",
        "Pedro Vite",
        "Jordy Alcívar",
        "Denil Castillo",
        "Pervis Estupiñán",
        "Piero Hincapié",
        "Willian Pacho",
        "Félix Torres",
        "Joel Ordóñez",
        "Ángelo Preciado",
        "Jackson Porozo",
        "Hernán Galíndez",
        "Moisés Ramírez",
        "Gonzalo Valle"
    ],
    "EGY": [
        "Mohamed Salah",
        "Omar Marmoush",
        "Trézéguet",
        "Zizo",
        "Ibrahim Adel",
        "Haissem Hassan",
        "Hamza Abdelkarim",
        "Emam Ashour",
        "Mostafa Abdelraouf Ziko",
        "Marwan Attia",
        "Mohanad Lasheen",
        "Mahmoud Saber",
        "Nabil Emad",
        "Mohamed Abdelmonem",
        "Hamdy Fathy",
        "Ramy Rabia",
        "Mohamed Hany",
        "Ahmed Fatouh",
        "Yasser Ibrahim",
        "Hossam Abdelmaguid",
        "Karim Hafez",
        "Tarek Alaa",
        "Mohamed El Shenawy",
        "Mostafa Shobeir",
        "Mohamed Alaa",
        "El Mahdy Soliman"
    ],
    "ENG": [
        "Harry Kane",
        "Ollie Watkins",
        "Ivan Toney",
        "Bukayo Saka",
        "Marcus Rashford",
        "Anthony Gordon",
        "Noni Madueke",
        "Jude Bellingham",
        "Eberechi Eze",
        "Morgan Rogers",
        "Declan Rice",
        "Kobbie Mainoo",
        "Elliot Anderson",
        "Jordan Henderson",
        "Reece James",
        "Marc Guéhi",
        "John Stones",
        "Ezri Konsa",
        "Dan Burn",
        "Jarell Quansah",
        "Tino Livramento",
        "Djed Spence",
        "Nico O'Reilly",
        "Jordan Pickford",
        "Dean Henderson",
        "James Trafford"
    ],
    "ESP": [
        "Lamine Yamal",
        "Nico Williams",
        "Mikel Oyarzabal",
        "Ferran Torres",
        "Dani Olmo",
        "Yéremy Pino",
        "Borja Iglesias",
        "Víctor Muñoz",
        "Álex Baena",
        "Pedri",
        "Gavi",
        "Mikel Merino",
        "Fabián Ruiz",
        "Rodri",
        "Martín Zubimendi",
        "Marcos Llorente",
        "Pedro Porro",
        "Alejandro Grimaldo",
        "Marc Cucurella",
        "Aymeric Laporte",
        "Pau Cubarsí",
        "Eric García",
        "Marc Pubill",
        "Unai Simón",
        "David Raya",
        "Joan García"
    ],
    "FRA": [
        "Kylian Mbappé",
        "Ousmane Dembélé",
        "Marcus Thuram",
        "Jean-Philippe Mateta",
        "Bradley Barcola",
        "Michael Olise",
        "Rayan Cherki",
        "Maghnes Akliouche",
        "Désiré Doué",
        "Warren Zaïre-Emery",
        "Adrien Rabiot",
        "Aurélien Tchouaméni",
        "Manu Koné",
        "N'Golo Kanté",
        "Théo Hernández",
        "Jules Koundé",
        "William Saliba",
        "Dayot Upamecano",
        "Ibrahima Konaté",
        "Lucas Hernández",
        "Maxence Lacroix",
        "Malo Gusto",
        "Lucas Digne",
        "Mike Maignan",
        "Brice Samba",
        "Robin Risser"
    ],
    "GER": [
        "Kai Havertz",
        "Nick Woltemade",
        "Deniz Undav",
        "Maximilian Beier",
        "Florian Wirtz",
        "Jamal Musiala",
        "Leroy Sané",
        "Jamie Leweling",
        "Lennart Karl",
        "Leon Goretzka",
        "Aleksandar Pavlović",
        "Angelo Stiller",
        "Felix Nmecha",
        "Pascal Groß",
        "Nadiem Amiri",
        "Joshua Kimmich",
        "Antonio Rüdiger",
        "Jonathan Tah",
        "Nico Schlotterbeck",
        "Waldemar Anton",
        "Malick Thiaw",
        "David Raum",
        "Nathaniel Brown",
        "Manuel Neuer",
        "Oliver Baumann",
        "Alexander Nübel"
    ],
    "GHA": [
        "Jordan Ayew",
        "Antoine Semenyo",
        "Iñaki Williams",
        "Ernest Nuamah",
        "Christopher Bonsu Baah",
        "Brandon Thomas-Asante",
        "Prince Kwabena Adu",
        "Abdul Fatawu Issahaku",
        "Kamaldeen Sulemana",
        "Augustine Boakye",
        "Thomas Partey",
        "Elisha Owusu",
        "Caleb Yirenkyi",
        "Kwasi Sibo",
        "Abdul Rahman Baba",
        "Gideon Mensah",
        "Alexander Djiku",
        "Alidu Seidu",
        "Jerome Opoku",
        "Jonas Adjetey",
        "Abdul Mumin",
        "Kojo Peprah Oppong",
        "Marvin Senaya",
        "Lawrence Ati-Zigi",
        "Benjamin Asare",
        "Solomon Agbasi",
        "Joseph Anang",
        "Paul Reverson"
    ],
    "HAI": [
        "Frantzdy Pierrot",
        "Duckens Nazon",
        "Wilson Isidor",
        "Ruben Providence",
        "Don Deedson Louicius",
        "Josué Casimir",
        "Derrick Etienne",
        "Yassin Fortuné",
        "Lenny Joseph",
        "Jean-Ricner Bellegarde",
        "Danley Jean Jacques",
        "Carl Fred Sainté",
        "Leverton Pierre",
        "Woodensky Pierre",
        "Dominique Simon",
        "Carlens Arcus",
        "Jean-Kévin Duverne",
        "Ricardo Adé",
        "Hannes Delcroix",
        "Duke Lacroix",
        "Wilguens Paugain",
        "Martin Expérience",
        "Keeto Thermoncy",
        "Johny Placide",
        "Alexandre Pierre",
        "Josué Duverger"
    ],
    "IRN": [
        "Mehdi Taremi",
        "Mehdi Ghayedi",
        "Amirhossein Hosseinzadeh",
        "Ali Alipour",
        "Dennis Dargahi",
        "Hadi Habibinejad",
        "Amirhossein Mahmoudi",
        "Kasra Taheri",
        "Alireza Jahanbakhsh",
        "Saman Ghoddos",
        "Mohammad Mohebi",
        "Mehdi Torabi",
        "Saeid Ezatolahi",
        "Rouzbeh Cheshmi",
        "Omid Noorafkan",
        "Mohammad Ghorbani",
        "Amirmohammad Razzaghinia",
        "Aria Yousefi",
        "Ehsan Hajsafi",
        "Milad Mohammadi",
        "Ramin Rezaeian",
        "Hossein Kanaanizadegan",
        "Shojae Khalilzadeh",
        "Saleh Hardani",
        "Ali Nemati",
        "Danial Eiri",
        "Alireza Beiranvand",
        "Payam Niazmand",
        "Hossein Hosseini",
        "Mohammad Khalifeh"
    ],
    "IRQ": [
        "Aymen Hussein",
        "Mohanad Ali",
        "Ali Al-Hamadi",
        "Montader Madjed",
        "Danilo Al-Saed",
        "Pashang Abdulla",
        "Louai Al-Ani",
        "Zidane Iqbal",
        "Ibrahim Bayesh",
        "Amir Al-Ammari",
        "Youssef Amyn",
        "Bashar Resan",
        "Osama Rashid",
        "Safaa Hadi",
        "Ali Jasim",
        "Rebin Sulaka",
        "Merchas Doski",
        "Zaid Tahseen",
        "Ali Adnan",
        "Frans Putros",
        "Saad Natiq",
        "Manaf Younis",
        "Hussein Ali",
        "Jalal Hassan",
        "Fahad Talib",
        "Ahmed Basil"
    ],
    "JOR": [
        "Mousa Al-Tamari",
        "Ali Olwan",
        "Mohammad Abu Zrayq",
        "Odeh Al-Fakhouri",
        "Ibrahim Sabra",
        "Ali Azaizeh",
        "Mahmoud Al-Mardi",
        "Noor Al-Rawabdeh",
        "Nizar Al-Rashdan",
        "Mohannad Abu Taha",
        "Yousef Qashi",
        "Mohammad Taha",
        "Rajaei Ayed",
        "Ibrahim Sadeh",
        "Mohammad Abu Hashish",
        "Amer Jamous",
        "Mohammad Al-Dawoud",
        "Ihsan Haddad",
        "Yazan Al-Arab",
        "Abdallah Nasib",
        "Saed Al-Rosan",
        "Husam Abu Dahab",
        "Mo Abualnadi",
        "Salim Obaid",
        "Anas Badawi",
        "Yazeed Abulaila",
        "Abdallah Al-Fakhouri",
        "Nour Bani Attiah"
    ],
    "JPN": [
        "Ayase Ueda",
        "Daizen Maeda",
        "Koki Ogawa",
        "Keisuke Goto",
        "Kento Shiogai",
        "Takefusa Kubo",
        "Ritsu Doan",
        "Junya Ito",
        "Keito Nakamura",
        "Daichi Kamada",
        "Ao Tanaka",
        "Yuito Suzuki",
        "Wataru Endo",
        "Kaishu Sano",
        "Junnosuke Suzuki",
        "Takehiro Tomiyasu",
        "Ko Itakura",
        "Hiroki Ito",
        "Tsuyoshi Watanabe",
        "Ayumu Seko",
        "Yukinari Sugawara",
        "Yuto Nagatomo",
        "Shogo Taniguchi",
        "Zion Suzuki",
        "Keisuke Osako",
        "Tomoki Hayakawa"
    ],
    "KOR": [
        "Son Heung-min",
        "Cho Gue-sung",
        "Oh Hyeon-gyu",
        "Lee Ki-hyuk",
        "Hwang Hee-chan",
        "Lee Kang-in",
        "Bae Jun-ho",
        "Yang Hyun-jun",
        "Lee Dong-gyeong",
        "Jens Castrop",
        "Lee Jae-sung",
        "Hwang In-beom",
        "Paik Seung-ho",
        "Kim Jin-gyu",
        "Eom Ji-sung",
        "Kim Min-jae",
        "Kim Moon-hwan",
        "Seol Young-woo",
        "Lee Tae-seok",
        "Park Jin-seob",
        "Kim Tae-hyeon",
        "Lee Han-beom",
        "Cho Wi-je",
        "Kim Seung-gyu",
        "Jo Hyeon-woo",
        "Song Bum-keun"
    ],
    "KSA": [
        "Firas Al-Buraikan",
        "Saleh Al-Shehri",
        "Abdullah Al-Hamdan",
        "Khalid Al-Ghannam",
        "Salem Al-Dawsari",
        "Musab Al-Juwayr",
        "Ayman Yahya",
        "Ziyad Al-Johani",
        "Sultan Mandash",
        "Alaa Al-Hejji",
        "Nasser Al-Dawsari",
        "Mohamed Kanno",
        "Abdullah Al-Khaibari",
        "Saud Abdulhamid",
        "Hassan Al-Tambakti",
        "Abdulelah Al-Amri",
        "Nawaf Boushal",
        "Ali Lajami",
        "Ali Majrashi",
        "Hassan Kadesh",
        "Moteb Al-Harbi",
        "Jehad Thakri",
        "Mohammed Abu Al-Shamat",
        "Mohammed Al-Owais",
        "Nawaf Al-Aqidi",
        "Ahmed Al-Kassar"
    ],
    "MAR": [
        "Ayoub El Kaabi",
        "Soufiane Rahimi",
        "Brahim Díaz",
        "Abde Ezzalzouli",
        "Chemsdine Talbi",
        "Ayoube Amaimouni",
        "Gessime Yassine",
        "Bilal El Khannouss",
        "Azzedine Ounahi",
        "Ismael Saibari",
        "Neil El Aynaoui",
        "Sofyan Amrabat",
        "Samir El Mourabet",
        "Ayyoub Bouaddi",
        "Achraf Hakimi",
        "Noussair Mazraoui",
        "Nayef Aguerd",
        "Chadi Riad",
        "Issa Diop",
        "Zakaria El Ouahdi",
        "Anass Salah-Eddine",
        "Youssef Belammari",
        "Redouane Halhal",
        "Yassine Bounou",
        "Munir Mohamedi",
        "Ahmed Reda Tagnaouti"
    ],
    "MEX": [
        "Raúl Jiménez",
        "Santiago Giménez",
        "Julián Quiñones",
        "Guillermo Martínez",
        "Armando González",
        "Alexis Vega",
        "César Huerta",
        "Roberto Alvarado",
        "Orbelín Pineda",
        "Gilberto Mora",
        "Álvaro Fidalgo",
        "Brian Gutiérrez",
        "Luis Chávez",
        "Edson Álvarez",
        "Luis Romo",
        "Érik Lira",
        "Obed Vargas",
        "Jesús Gallardo",
        "Jorge Sánchez",
        "Johan Vásquez",
        "César Montes",
        "Israel Reyes",
        "Mateo Chávez",
        "Guillermo Ochoa",
        "Raúl Rangel",
        "Carlos Acevedo"
    ],
    "NED": [
        "Memphis Depay",
        "Cody Gakpo",
        "Wout Weghorst",
        "Brian Brobbey",
        "Donyell Malen",
        "Noa Lang",
        "Crysencio Summerville",
        "Justin Kluivert",
        "Tijjani Reijnders",
        "Frenkie de Jong",
        "Ryan Gravenberch",
        "Quinten Timber",
        "Teun Koopmeiners",
        "Guus Til",
        "Mats Wieffer",
        "Marten de Roon",
        "Virgil van Dijk",
        "Nathan Aké",
        "Denzel Dumfries",
        "Jurriën Timber",
        "Micky van de Ven",
        "Jorrel Hato",
        "Jan Paul van Hecke",
        "Bart Verbruggen",
        "Mark Flekken",
        "Robin Roefs"
    ],
    "NOR": [
        "Erling Haaland",
        "Alexander Sørloth",
        "Jørgen Strand Larsen",
        "Antonio Nusa",
        "Oscar Bobb",
        "Martin Ødegaard",
        "Andreas Schjelderup",
        "Thelo Aasgaard",
        "Jens Petter Hauge",
        "Sander Berge",
        "Patrick Berg",
        "Kristian Thorstvedt",
        "Morten Thorsby",
        "Fredrik Aursnes",
        "Kristoffer Ajer",
        "Julian Ryerson",
        "Leo Østigård",
        "David Møller Wolfe",
        "Marcus Holmgren Pedersen",
        "Torbjørn Heggem",
        "Fredrik Bjørkan",
        "Henrik Falchener",
        "Sondre Langås",
        "Ørjan Nyland",
        "Egil Selvik",
        "Sander Tangvik"
    ],
    "NZL": [
        "Chris Wood",
        "Ben Waine",
        "Kosta Barbarouses",
        "Callum McCowatt",
        "Jesse Randall",
        "Eli Just",
        "Ben Old",
        "Lachlan Bayliss",
        "Sarpreet Singh",
        "Marko Stamenic",
        "Matt Garbett",
        "Ryan Thomas",
        "Joe Bell",
        "Alex Rufer",
        "Liberato Cacace",
        "Tyler Bindon",
        "Nando Pijnaker",
        "Michael Boxall",
        "Finn Surman",
        "Tommy Smith",
        "Tim Payne",
        "Francis De Vries",
        "Callan Elliot",
        "Max Crocombe",
        "Alex Paulsen",
        "Michael Woud"
    ],
    "PAN": [
        "Ismael Díaz",
        "Cecilio Waterman",
        "José Fajardo",
        "Tomás Rodríguez",
        "Alberto Quintero",
        "José Luis Rodríguez",
        "Yoel Bárcenas",
        "Adalberto Carrasquilla",
        "Azarías Londoño",
        "Cristian Martínez",
        "Carlos Harvey",
        "César Yanis",
        "Aníbal Godoy",
        "Michael Amir Murillo",
        "Eric Davis",
        "César Blackman",
        "José Córdoba",
        "Fidel Escobar",
        "Andrés Andrade",
        "Edgardo Fariña",
        "Jiovany Ramos",
        "Roderick Miller",
        "Jorge Gutiérrez",
        "Orlando Mosquera",
        "Luis Mejía",
        "César Samudio"
    ],
    "PAR": [
        "Alex Arce",
        "Gabriel Ávalos",
        "Antonio Sanabria",
        "Julio Enciso",
        "Miguel Almirón",
        "Ramón Sosa",
        "Diego Gómez",
        "Damián Bobadilla",
        "Mathías Villasanti",
        "Andrés Cubas",
        "Matías Galarza",
        "Gustavo Caballero",
        "Alejandro Romero Gamarra",
        "Braian Ojeda",
        "Maurício",
        "Gustavo Gómez",
        "Junior Alonso",
        "Fabián Balbuena",
        "Omar Alderete",
        "Alan Benítez",
        "Juan Cáceres",
        "Gustavo Velázquez",
        "Alexandro Maidana",
        "Roberto Junior Fernández",
        "Orlando Gill",
        "Gastón Olveira"
    ],
    "POR": [
        "Cristiano Ronaldo",
        "Gonçalo Ramos",
        "Rafael Leão",
        "Pedro Neto",
        "João Félix",
        "Francisco Conceição",
        "Gonçalo Guedes",
        "Bernardo Silva",
        "Bruno Fernandes",
        "Francisco Trincão",
        "Vitinha",
        "João Neves",
        "Rúben Neves",
        "Matheus Nunes",
        "Samu Costa",
        "Nuno Mendes",
        "João Cancelo",
        "Diogo Dalot",
        "Rúben Dias",
        "Gonçalo Inácio",
        "Renato Veiga",
        "Tomás Araújo",
        "Nélson Semedo",
        "Diogo Costa",
        "Rui Silva",
        "José Sá"
    ],
    "QAT": [
        "Almoez Ali",
        "Akram Afif",
        "Hassan Al-Haydos",
        "Mohammed Muntari",
        "Yusuf Abdurisag",
        "Ahmed Alaaeldin",
        "Edmilson Junior",
        "Ahmed Al-Ganehi",
        "Abdulaziz Hatem",
        "Karim Boudiaf",
        "Assim Madibo",
        "Ahmed Fathy",
        "Jassem Gaber",
        "Mohamed Al-Mannai",
        "Tahsin Jamshid",
        "Boualem Khoukhi",
        "Pedro Miguel",
        "Homam Ahmed",
        "Lucas Mendes",
        "Sultan Al-Brake",
        "Al-Hashmi Al-Hussain",
        "Ayoub Al-Oui",
        "Issa Laye",
        "Rayyan Al-Ali",
        "Meshaal Barsham",
        "Salah Zakaria",
        "Mahmud Abunada",
        "Shehab Ellethy"
    ],
    "RSA": [
        "Lyle Foster",
        "Evidence Makgopa",
        "Iqraam Rayners",
        "Relebohile Mofokeng",
        "Themba Zwane",
        "Oswin Appollis",
        "Thapelo Maseko",
        "Tshepang Moremi",
        "Teboho Mokoena",
        "Sphephelo Sithole",
        "Thalente Mbatha",
        "Jayden Adams",
        "Aubrey Modiba",
        "Khuliso Mudau",
        "Nkosinathi Sibisi",
        "Mbekezeli Mbokazi",
        "Ime Okon",
        "Samukele Kabini",
        "Khulumani Ndamane",
        "Thabang Matuludi",
        "Kamogelo Sebelebele",
        "Bradley Cross",
        "Olwethu Makhanya",
        "Ronwen Williams",
        "Ricardo Goss",
        "Sipho Chaine"
    ],
    "SCO": [
        "Ché Adams",
        "Lyndon Dykes",
        "George Hirst",
        "Lawrence Shankland",
        "Ross Stewart",
        "Scott McTominay",
        "John McGinn",
        "Ryan Christie",
        "Ben Gannon-Doak",
        "Findlay Curtis",
        "Lewis Ferguson",
        "Kenny McLean",
        "Tyler Fletcher",
        "Andy Robertson",
        "Kieran Tierney",
        "Jack Hendry",
        "Grant Hanley",
        "John Souttar",
        "Scott McKenna",
        "Aaron Hickey",
        "Nathan Patterson",
        "Anthony Ralston",
        "Dominic Hyam",
        "Craig Gordon",
        "Angus Gunn",
        "Liam Kelly"
    ],
    "SEN": [
        "Sadio Mané",
        "Ismaïla Sarr",
        "Iliman Ndiaye",
        "Nicolas Jackson",
        "Bamba Dieng",
        "Chérif Ndiaye",
        "Ibrahima Mbaye",
        "Assane Diao",
        "Pape Matar Sarr",
        "Habib Diarra",
        "Lamine Camara",
        "Idrissa Gueye",
        "Pape Gueye",
        "Pathé Ciss",
        "Bara Sapoko Ndiaye",
        "Krépin Diatta",
        "Kalidou Koulibaly",
        "Moussa Niakhaté",
        "Ismail Jakobs",
        "Abdoulaye Seck",
        "El Hadji Malick Diouf",
        "Mamadou Sarr",
        "Antoine Mendy",
        "Ilay Camara",
        "Moustapha Mbow",
        "Édouard Mendy",
        "Mory Diaw",
        "Yehvann Diouf"
    ],
    "SUI": [
        "Breel Embolo",
        "Noah Okafor",
        "Dan Ndoye",
        "Zeki Amdouni",
        "Cedric Itten",
        "Rubén Vargas",
        "Christian Fassnacht",
        "Fabian Rieder",
        "Johan Manzambi",
        "Ardon Jashari",
        "Granit Xhaka",
        "Remo Freuler",
        "Denis Zakaria",
        "Djibril Sow",
        "Michel Aebischer",
        "Manuel Akanji",
        "Nico Elvedi",
        "Ricardo Rodríguez",
        "Silvan Widmer",
        "Miro Muheim",
        "Aurèle Amenda",
        "Eray Cömert",
        "Luca Jaquez",
        "Gregor Kobel",
        "Yvon Mvogo",
        "Marvin Keller"
    ],
    "SWE": [
        "Alexander Isak",
        "Viktor Gyökeres",
        "Benjamin Nygren",
        "Gustaf Nilsson",
        "Anthony Elanga",
        "Ken Sema",
        "Alexander Bernhardsson",
        "Taha Ali",
        "Lucas Bergvall",
        "Yasin Ayari",
        "Mattias Svanberg",
        "Besfort Zeneli",
        "Jesper Karlström",
        "Victor Lindelöf",
        "Isak Hien",
        "Gabriel Gudmundsson",
        "Daniel Svensson",
        "Hjalmar Ekdal",
        "Carl Starfelt",
        "Gustaf Lagerbielke",
        "Herman Johansson",
        "Eric Smith",
        "Elliot Stroud",
        "Jacob Widell Zetterström",
        "Viktor Johansson",
        "Kristoffer Nordfeldt"
    ],
    "TUN": [
        "Elias Achouri",
        "Firas Chaouat",
        "Hazem Mastouri",
        "Elias Saad",
        "Sebastian Tounekti",
        "Khalil Ayari",
        "Rayan Elloumi",
        "Hannibal Mejbri",
        "Ismaël Gharbi",
        "Anis Ben Slimane",
        "Ellyes Skhiri",
        "Rani Khedira",
        "Mortadha Ben Ouanes",
        "Hadj Mahmoud",
        "Montassar Talbi",
        "Dylan Bronn",
        "Ali Abdi",
        "Yan Valery",
        "Mohamed Amine Ben Hamida",
        "Moutaz Neffati",
        "Omar Rekik",
        "Adem Arous",
        "Raed Chikhaoui",
        "Aymen Dahmen",
        "Sabri Ben Hessen",
        "Mouhib Chamakh"
    ],
    "TUR": [
        "Kenan Yıldız",
        "Arda Güler",
        "Kerem Aktürkoğlu",
        "Barış Alper Yılmaz",
        "Yunus Akgün",
        "İrfan Can Kahveci",
        "Oğuz Aydın",
        "Deniz Gül",
        "Yusuf Sarı",
        "Can Uzun",
        "Aral Şimşir",
        "Hakan Çalhanoğlu",
        "Orkun Kökçü",
        "Kaan Ayhan",
        "İsmail Yüksek",
        "Salih Özcan",
        "Atakan Karazor",
        "Demir Ege Tıknaz",
        "Merih Demiral",
        "Zeki Çelik",
        "Çağlar Söyüncü",
        "Mert Müldür",
        "Ferdi Kadıoğlu",
        "Ozan Kabak",
        "Abdülkerim Bardakcı",
        "Eren Elmalı",
        "Samet Akaydın",
        "Yusuf Akçiçek",
        "Mustafa Eskihellaç",
        "Ahmetcan Kaplan",
        "Uğurcan Çakır",
        "Mert Günok",
        "Altay Bayındır",
        "Ersin Destanoğlu",
        "Muhammed Şengezer"
    ],
    "URU": [
        "Darwin Núñez",
        "Federico Viñas",
        "Rodrigo Aguirre",
        "Giorgian de Arrascaeta",
        "Facundo Pellistri",
        "Nicolás de la Cruz",
        "Brian Rodríguez",
        "Maximiliano Araújo",
        "Agustín Canobbio",
        "Federico Valverde",
        "Rodrigo Bentancur",
        "Manuel Ugarte",
        "Rodrigo Zalazar",
        "Guillermo Varela",
        "Nahitan Nández",
        "Ronald Araújo",
        "José María Giménez",
        "Sebastián Cáceres",
        "Santiago Bueno",
        "Mathías Olivera",
        "Joaquín Piquerez",
        "Matías Viña",
        "Fernando Muslera",
        "Sergio Rochet",
        "Santiago Mele"
    ],
    "USA": [
        "Christian Pulisic",
        "Folarin Balogun",
        "Ricardo Pepi",
        "Haji Wright",
        "Brenden Aaronson",
        "Gio Reyna",
        "Tim Weah",
        "Alejandro Zendejas",
        "Malik Tillman",
        "Weston McKennie",
        "Sebastian Berhalter",
        "Tyler Adams",
        "Cristian Roldan",
        "Sergiño Dest",
        "Antonee Robinson",
        "Alex Freeman",
        "Joe Scally",
        "Max Arfsten",
        "Chris Richards",
        "Mark McKenzie",
        "Miles Robinson",
        "Auston Trusty",
        "Tim Ream",
        "Matt Freese",
        "Matt Turner",
        "Chris Brady"
    ],
    "UZB": [
        "Eldor Shomurodov",
        "Igor Sergeev",
        "Abbosbek Fayzullaev",
        "Oston Urunov",
        "Jasur Yakhshiboev",
        "Sherzod Temirov",
        "Aziz Amonov",
        "Jaloliddin Masharipov",
        "Hojimat Erkinov",
        "Azizbek Turgunboev",
        "Diyor Kholmatov",
        "Otabek Shukurov",
        "Odiljon Hamrobekov",
        "Jamshid Iskanderov",
        "Sherzod Esanov",
        "Akmal Mozgovoy",
        "Aziz Ganiev",
        "Abdukodir Khusanov",
        "Rustam Ashurmatov",
        "Husniddin Aliqulov",
        "Umar Eshmurodov",
        "Abdulla Abdullaev",
        "Sherzod Nasrullaev",
        "Farrukh Sayfiev",
        "Utkir Yusupov",
        "Botirali Ergashev"
    ]
}


def main() -> None:
    codes = sorted({c for teams in official_wc2026_group_teams().values() for c, _ in teams})
    assert len(codes) == 48
    missing = [c for c in codes if c not in POOLS]
    extra = [c for c in POOLS if c not in codes]
    if missing or extra:
        raise SystemExit(f"code mismatch vs official groups: missing={missing} extra={extra}")
    _OUT.write_text(json.dumps(POOLS, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {_OUT} ({len(POOLS)} teams, {sum(len(v) for v in POOLS.values())} players)")


if __name__ == "__main__":
    main()
